### ISSUE TITLE
Clicking a Radial Menu Item when using AHSS/APG causes player to attack

### ISSUE THREAD

**Issue by rc174945** [AoTTG-2/Aottg2-Unity#9]
Prevent left click from activating attack when clicking emotes

**Comment by gisketch** [comment]
https://github.com/AoTTG-2/Aottg2-Unity/assets/78424395/4b55ea84-5d91-4ddc-ba2f-7eb62ecdba60

_Removed the CD in the video._

Been trying to replicate this, but cannot. The last three times the character did attack in the video was when i double clicked it quick. Could be a mouse hardware problem for some? Would like to confirm if this still occurs on you guys' end?

**Comment by Adonca2203** [comment]
I've also been trying to replicate this and the only time he attacks is when I double click not sure how fixable this is if we can't reproduce it

**Comment by BLuRTuts** [comment]
For the record. This also happens with all cl inputs while in any menu or chat. Don't know if that should be fixed as well

**Comment by Adonca2203** [comment]
Have we found a way to reliably reproduce this? Why was it reopened?

**Comment by Z-XINY** [comment]
> Have we found a way to reliably reproduce this? Why was it reopened?

You can try clicking emotes when using AHSS weapon. I can actually only replicate this bug when using AHSS.

Uploading Aottest_bug_-_Trim.mp4…
